### ISSUE TITLE
URL too long

### ISSUE THREAD

**Issue by satip** [Woersty/LoxBerry-Plugin-https2http#1]
is there a character limit?
i am using a telegram bot and want to use them via loxone (it is working fine via fhem)
it seems it does not work if the URL is longer than 196 Characters

example:
http://[loxberry-IP]/plugins/https2http/?url=https%3A%2F%2Fapi.telegram.org%2Fbot[BOT-ID]w%2FsendMessage%3Fchat_id[CHAT-ID]text%3D[MY%20TEXT%20MESSAGE]

maybe it is not a plugin-problem rather than a loxone-problem?

**Comment by Woersty** [comment]
Goes quick and dirty via Shell command.
Maybe it is related to that fact- let me check.
I keep you posted...

**Comment by Woersty** [comment]
Please try v0.6

**Comment by satip** [comment]
THX - it is working now
