### ISSUE TITLE
Authentication with @ in user name failes

### ISSUE THREAD

**Issue by TheRomsen** [Woersty/LoxBerry-Plugin-https2http#3]
I'll try to call a https website with the authentication via the URL where my user name has the @ inside to get some JSON data back.
E.g. https://myname@email.com:mySecurePassword@backend.givemejson.data/value?bla=blub

Within the normal browser it is working but the plugin tells me:
`ERROR: PHP: Fehler beim Verarbeiten der Daten mit cURL. (https://myname@email.com:mySecurePassword@backend.givemejson.data/value?bla=blub)[]`
If I use curl manually then it works with using the % notation of the @:

`curl https://myname%40email.com:mySecurePassword@backend.givemejson.data/value?bla=blub`

Can you please have a look?

Thanks in advance.

**Comment by Woersty** [comment]
Will have a look

**Comment by Emuench1** [comment]
I have the same problem! what is the solution?

**Comment by Woersty** [comment]
I think it should work now. Couldn't test deeper.

**Comment by Emuench1** [comment]
Bei  mir geht es um dies Seite 

https://eu5.fusionsolar.huawei.com/unisso/login.action?service=%2Funisess%2Fv1%2Fauth%3Fservice%3D%252Fnetecowebext%252Fhome%252Findex.html#/LOGIN

Ich komme da nicht weiter mit anderen Seiten funktioniert es 

Gruß Enrico

**Comment by Woersty** [comment]
Haste die Version von gestern probiert?

**Comment by Emuench1** [comment]
Ja da bekomme ich immer nur ein weises Tab

**Comment by Emuench1** [comment]
Ich habe jetzt schon einiges versucht aber ich bekomme immer nur ein leeres Tab. Es gibt auch ein Kiosk Modus ohne Passwort das funktioniert auch nicht.
Würde immer noch um die Huawei Seite gehen.

https://eu5.fusionsolar.huawei.com/unisso/login.action?decision=1&service=https%3A%2F%2Fregion02eu5.fusionsolar.huawei.com%2Funisess%2Fv1%2Fauth%3Fservice%3D%252Fpvmswebsite%252Fassets%252Fbuild%252Findex.html%2523%252Fhome%252Flist

Gruß Enrico
