### ISSUE TITLE
Fehler beim Verarbeiten der Daten mit cURL.

### ISSUE THREAD

**Issue by GuenWuen** [Woersty/LoxBerry-Plugin-https2http#4]
Mit der neuen Version bekomme ich folgenden Fehlerhinweis

`Fehler beim Verarbeiten der Daten mit cURL. (https://www.clever-tanken.de/tankstelle_details/53438) []`

Die aufgerufende Seite lautet:
`http://[IP-LOXBERRY/plugins/https2http/?url=https%3A%2F%2Fwww.clever-tanken.de%2Ftankstelle_details%2F53438](http://IP-LOXBERRY/plugins/https2http/?url=https%3A%2F%2Fwww.clever-tanken.de%2Ftankstelle_details%2F53438)`

Die Seite die genutzt wird:
[https://www.clever-tanken.de/tankstelle_details/25887](url)

**Comment by Woersty** [comment]
Dann probiere ich es nachher mal auf meinem System. Hatte das ‚trocken‘ programmiert ohne zu testen 🫣

**Comment by XaviCabestany** [comment]
Hi, 
Same error to me. I'm using a simple search at google (https://www.google.com/search?q=tiempo+igualada)
Stopped working with the auto-update funtion of loxberry.

**Comment by serecords** [comment]
Ich schließe mich dem an, es kommt die von GuenWuen beschriebene Fehlermeldung. Bei mir beim Aufruf der Telegram API - aber das ist vermutlich nicht relevant, da das Problem auch mit anderen Seiten besteht.

**Comment by servicemensch** [comment]
Ich habe das gleiche Problem seit dem letzten update.

**Comment by XaviCabestany** [comment]
Alguna solucion de cara a Loxberry? se puede hacer un downgrade? Me han dejado de funcionar algunas entradas.

**Comment by istoOi** [comment]
Selber Fehler hier mit Version 2023.07.31

(2021.03.09 funktioniert)

**Comment by servicemensch** [comment]
Fehler liegt an der Änderung um Basic-Auth im Request zu unterstützen. Durch Rückgängig machen der Änderung an der Index.php lässt sich der Fehler umgehen.

**Comment by bastelbert** [comment]
Gleicher Fehler bei mir mit Version 2023.07.31

**Comment by Woersty** [comment]
Please test again. Bitte nochmal testen. (nach/after Autoupdate)

**Comment by GuenWuen** [comment]
Danke @Woersty - getestet und für gut befunden :-D
